# SPDX-FileCopyrightText: 2026 Oscar Bender-Stone <oscar-bender-stone@protonmail.com>
# SPDX-License-Identifier: MIT

version = 2

[[annotations]]
path = "Cargo.lock"
SPDX-FileCopyrightText = "2026 Oscar Bender-Stone <oscar-bender-stone@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"
