# SPDX-FileCopyrightText: 2026 Oscar Bender-Stone <oscar-bender-stone@protonmail.com>
# SPDX-License-Identifier: MIT

[package]
name = "kedge-test"
edition = "2024"
version.workspace = true

[dependencies]
proptest = { version = "1.10.0", features = ["proptest-macro"] }
